sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"abc\",\"password\":\"123\"},{\"id\":9, \"username\":\"abc\",\"password\":\"123\"},{\"id\":10, \"username\":\"ABC\",\"password\":\"010\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.232.133
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8101    
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh      